stages:
  - build
  - update_helm_chart

variables:
  APP_NAME: student-web-cont
  IMAGE_TAG: tienshawn/$APP_NAME:$CI_COMMIT_TAG

build_images:
  image: docker:24.0.0
  stage: build
  services:
    - docker:24.0.0-dind

  script:
    - echo "${CI_REGISTRY_USER}  ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

  rules:
    - if: $CI_COMMIT_TAG


#update helm values
update_helm_chart:
  stage: update_helm_chart
  image: ubuntu:22.04
  before_script:
    #Git
    - apt-get update -y && apt-get install git -y
    - git config --global user.email "tiennguyen14122003@gmail.com"
    - git config --global user.name "tienshawn"
    - git clone https://github.com/tienshawn/helm-web-values.git
    - cd helm-web-values

  script:
  # Update Image TAG
    - sed -i "s/student-web-cont:.*/student-web-cont:${CI_COMMIT_TAG}/g" values.yaml
    - git remote add github_origin https://${GH_REPO_TOKEN}@github.com/tienshawn/helm-web-values.git
    - git add values.yaml
    - git commit -m "Update Image Version"
    - git push github_origin HEAD:main

  rules:
    - if: $CI_COMMIT_TAG

