- name: Run docker image {{ web_image_name }}:{{ web_image_tag }}
  docker_container:
    name: "{{ web_container_name }}"
    image: "{{ web_image_name }}:{{ web_image_tag }}"
    state: started
    restart_policy: unless-stopped
    ports: "{{ web_ports }}"
  become: true