# roles/db/tasks/main.yml

- name: Copy init data to remote host
  copy:
    src: "{{ init_data_src_dir }}"
    dest: "{{ init_data_dest_dir }}"
    owner: "{{ init_data_owner }}"
    group: "{{ init_data_group }}"
    mode: "{{ init_data_mode }}"
    remote_src: false

- name: Ensure init-data.sh is executable
  file:
    path: "{{ init_data_script_path }}"
    mode: "{{ init_data_mode }}"
    owner: "{{ init_data_owner }}"
    group: "{{ init_data_group }}"

- name: Check if docker network exists
  docker_network_info:
    name: "{{ docker_network_name }}"
  register: docker_network
  become: true

- name: Create docker network
  docker_network:
    name: "{{ docker_network_name }}"
    state: present
  when: docker_network.exists == false
  become: true

- name: Run docker image mongo:5.0
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image_name }}:{{ mongo_image_tag }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"
    hostname: "{{ mongo_hostname }}"
    ports: "{{ mongo_ports }}"
    volumes:
      - "{{ init_data_dest_dir }}attendees.json:/docker-entrypoint-initdb.d/attendees.json"
      - "{{ init_data_dest_dir }}init-data.sh:/docker-entrypoint-initdb.d/init-data.sh"
  become: true
