name: ci-cd web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checkout web-config repo
      uses: actions/checkout@v3
      with:
        repository: shukuchicoding/vdt_web-config
        token: ${{ secrets.PERSONAL_ACCESS_KEY }}
        path: .

    - name: Update values.yaml
      run: |
        sed -i 's/tag: .*/tag: ${{ github.ref_name }}/' ./values.yaml
 
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_KEY }}
      run: |
        git config --global user.name '${{ secrets.GITUSER_NAME }}'
        git config --global user.email '${{ secrets.GITUSER_EMAIL }}'
        git add .
        git commit -m "Update web image tag to ${{ github.ref_name }}"
        git push origin master

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        # context: .
        push: true
        tags: vietanhhust1404/web:${{ github.ref_name }}
