# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: cicd-api

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  deploy-local:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: vietanhhust1404/api:${{ github.ref_name }}


    - name: Checkout helm config repo
      uses: actions/checkout@v2
      with:
        repository: shukuchicoding/vdt-api-config
        token: ${{ secrets.PERSONAL_ACCESS_KEY }}
        path: .

    - name: Update values.yaml
      run: |
        sed -i 's/tag: .*/tag: ${{ github.ref_name }}/' ./values.yaml
 
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_KEY }}
      run: |
        git config --global user.name '${{ secrets.USER_NAME }}'
        git config --global user.email '${{ secrets.USER_EMAIL }}'
        git add -A
        git commit -m "Update api image tag to ${{ github.ref_name }}"
        git push origin master
