apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name: frontend1
        image: docker.io/tienshawn/test-web:3.0
        ports:
        - containerPort: 80
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.1.0
        args:
          - '--nginx.scrape-uri=http://127.0.0.1/stub_status'
        ports:
          - containerPort: 9113

---
apiVersion: v1
kind: Service
metadata:
  name: frontend1
spec:
  selector:
    app: frontend1
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 32007
  - name: metrics
    port: 9113
    targetPort: 9113
    nodePort: 32011