replicaCount: 1

image:
  repository: vietanhhust1404/web
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.0.0

service:
  type: NodePort
  port: 3000
  targetport: 3000
  nodePort: 30414

env:
  API: http://192.168.49.2:30415

container:
  name: web
ingress:
  enabled: false
serviceAccount:
  create: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80