- name: Pull Backend service image with a specific tag
  docker_image:
    name: "{{ api_image_name }}"
    tag: "{{ api_image_tag }}"
    source: pull

- name: Run API container
  docker_container:
    name: backend_container
    image: "{{ api_image_name }}:{{ api_image_tag }}"
    ports:
      - "{{ api_port }}:8080"
    env:
      SPRING_DATASOURCE_URL: "jdbc:mysql://{{ db_host }}:{{ db_port }}/{{ db_name }}"
      SPRING_DATASOURCE_USERNAME: "{{ db_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQL5Dialect"
    state: started
